import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { AppConfig } from '../types.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROMPT_PATH = path.join(__dirname, '..', '..', 'prompts', 'system.md');

let cachedPrompt: string | null = null;

function loadRawPrompt(): string {
  if (!cachedPrompt) {
    cachedPrompt = fs.readFileSync(PROMPT_PATH, 'utf-8');
  }
  return cachedPrompt;
}

/**
 * Build the system prompt by interpolating template variables from config.
 * Handles both {{VAR}} and [VAR] placeholder styles found in the prompt.
 */
export function buildSystemPrompt(config: AppConfig): string {
  let prompt = loadRawPrompt();

  const replacements: Record<string, string> = {
    // Double-brace style (used in example responses)
    '{{RICARDO_EMAIL}}': config.email.ricardo_email,
    '{{RETURN_DATE}}': config.absence.return_date,
    '{{FALLBACK_CONTACT_NAME}}': config.absence.fallback_contact_name,
    '{{FALLBACK_CONTACT_EMAIL}}': config.absence.fallback_contact_email,
    '{{RICARDO_SURNAME}}': config.absence.ricardo_surname,
    '{{CURRENT_DATE}}': new Date().toISOString().split('T')[0],
    // Bracket style (used in prose)
    '[SURNAME]': config.absence.ricardo_surname,
    '[RETURN DATE]': config.absence.return_date,
    '[RETURN_DATE]': config.absence.return_date,
    '[FALLBACK CONTACT NAME]': config.absence.fallback_contact_name,
    '[FALLBACK CONTACT]': config.absence.fallback_contact_name,
    '[FALLBACK EMAIL]': config.absence.fallback_contact_email,
    '[FALLBACK_CONTACT_EMAIL]': config.absence.fallback_contact_email,
  };

  for (const [placeholder, value] of Object.entries(replacements)) {
    if (value) {
      prompt = prompt.replaceAll(placeholder, value);
    }
  }

  return prompt;
}

/**
 * Build the PAAIR email footer appended to every outbound response.
 */
export function buildFooter(config: AppConfig): string {
  let footer =
    'This email includes AI generated content which may be incorrect.\n\n' +
    'This response was generated by PAAIR (Personal Assistant Artificial Intelligence for Ricardo), ' +
    "a locally hosted AI assistant running on Ricardo's personal machine. " +
    'PAAIR processes only the email content explicitly shared with it and does not retain conversation history beyond this exchange. ' +
    `If you would prefer a human response, please wait until after ${config.absence.return_date}`;

  if (config.absence.fallback_contact_name && config.absence.fallback_contact_email) {
    footer += ` or contact ${config.absence.fallback_contact_name} at ${config.absence.fallback_contact_email}`;
  }

  footer += '.';
  return footer;
}
