/**
 * Test script: sends a real email via Resend to verify delivery.
 * Usage: npx tsx scripts/test_resend.ts [recipient-email]
 * Defaults to sending to Ricardo's KCL address.
 */
import { Resend } from 'resend';
import { getConfig } from '../src/config.js';

const config = getConfig();
const recipient = process.argv[2] || config.email.ricardo_email;

if (!config.email.resend_api_key) {
  console.error('RESEND_API_KEY is not set in .env');
  process.exit(1);
}

const resend = new Resend(config.email.resend_api_key);

console.log(`Sending test email to: ${recipient}`);
console.log(`From: PAAIR <${config.email.paair_address}>`);
console.log(`CC: ${config.email.ricardo_email}`);

const { data, error } = await resend.emails.send({
  from: `PAAIR <${config.email.paair_address}>`,
  to: recipient,
  cc: recipient !== config.email.ricardo_email ? config.email.ricardo_email : undefined,
  subject: 'PAAIR Test Email',
  text: [
    'This is a test email from PAAIR.',
    '',
    'If you are reading this, the Resend integration is working correctly.',
    `Sent at: ${new Date().toISOString()}`,
    '',
    '---',
    'This response was generated by PAAIR (Personal Assistant Artificial Intelligence for Ricardo), ',
    "a locally hosted AI assistant running on Ricardo's personal machine.",
  ].join('\n'),
});

if (error) {
  console.error('Send failed:', error);
  process.exit(1);
}

console.log('Email sent successfully!');
console.log('Resend message ID:', data?.id);
console.log('\nCheck your inbox (and spam folder) for the test email.');
